language: node_js
dist: trusty
sudo: required
node_js: stable
before_script:
  - TAG=v0.12.3
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$TAG/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript
  - export PATH=$PATH:$HOME/purescript
install:
  - npm install
  - npm install -g bower
  - bower install --production
script:
  - npm run -s build
  - bower install
  - npm run -s test
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
